blog/urls.py
from django.conf.urls import url
from . import views
app_name = 'blog'
urlpatterns = [
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$',views.PostDetailView.as_view(),name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.ArchivesView.as_view(),name='archives'),
    url(r'^category/(?P<category>[0-9a-zA-Z\s]+)/$',views.CategoryView.as_view(),name='category'),
    url(r'^tag/(?P<tag>[0-9a-zA-Z\s]+)/$',views.TagView.as_view(),name='tag'),
    url(r'^about/$',views.about,name='about'),
    url(r'^search/$', views.search, name='search'),
]

blogproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('blog.urls')),
    url(r'',include('comments.urls')),
]

comments/urls.py
from django.conf.urls import url

from . import views

app_name = 'comments'

urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import markdown
from django.utils.html import strip_tags
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='类别名')
    def __str__(self):
        return self.name
    class Meta():
        verbose_name='类别'
        verbose_name_plural=verbose_name


class Tag(models.Model):
    name = models.CharField(max_length=100, verbose_name='标签名')
    def __str__(self):
        return self.name
    class Meta():
        verbose_name='标签'
        verbose_name_plural=verbose_name

class Post(models.Model):
    title = models.CharField(max_length=70, verbose_name='标题')
    body = models.TextField(verbose_name='正文')
    created_time = models.DateTimeField(auto_now_add=True,verbose_name='发布时间')
    modified_time = models.DateTimeField(auto_now=True,verbose_name='修改时间')
    excerpt = models.CharField(max_length=200, blank=True, verbose_name='摘要')
    category = models.ForeignKey(Category,verbose_name='类别')
    tags = models.ManyToManyField(Tag,blank=True,verbose_name='标签')
    author = models.ForeignKey(User,verbose_name='作者')
    views = models.PositiveIntegerField(default=0,verbose_name='浏览量')
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])
    def auto_excerpt(self):
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            self.excerpt = strip_tags(md.convert(self.body))[:55]
        self.save()
    class Meta():
        verbose_name='文章'
        verbose_name_plural=verbose_name
        ordering = ['-created_time']

comments/models.py
from django.db import models

# Create your models here.

class Comment(models.Model):
    """docstring for Comment."""
    name = models.CharField(max_length=100,verbose_name='用户名')
    email = models.EmailField(max_length=255,verbose_name='邮箱')
    url = models.URLField(blank=True,verbose_name='网站')
    text = models.TextField(verbose_name='留言内容')
    created_time = models.DateTimeField(auto_now_add=True,verbose_name='留言时间')
    post = models.ForeignKey('blog.Post',verbose_name='被留言文章')
    def __str__(self):
        return self.text[:25]
    class Meta():
    	verbose_name='评论'
    	verbose_name_plural=verbose_name

comments/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name','url','email','text']

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post,Category,Tag
import markdown
import pygments
from comments.forms import CommentForm
from django.views.generic import ListView,DetailView

# def index(request):
#     post_list = Post.objects.all().order_by('-created_time')
#     return render(request,'blog/index.html',context={'post_list':post_list})
class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 5


# def detail(request,pk):
#     post = get_object_or_404(Post,pk=pk)
#     post.increase_views()  #浏览量+1
#     post.body = markdown.markdown(post.body,extensions=[
#                                      'markdown.extensions.extra',
#                                      'markdown.extensions.codehilite',
#                                      'markdown.extensions.toc',
#                                   ])
#     form = CommentForm()
#     comment_list = post.comment_set.all()
#     context = {'post': post,
#                'form': form,
#                'comment_list': comment_list
#                }
#     return render(request, 'blog/detail.html', context=context)
class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        response = super(PostDetailView, self).get(request, *args, **kwargs)
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
        post = super(PostDetailView, self).get_object(queryset=None)
        post.body = markdown.markdown(post.body,
                                      extensions=[
                                          'markdown.extensions.extra',
                                          'markdown.extensions.codehilite',
                                          'markdown.extensions.toc',
                                      ])
        return post

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list
        })
        return context


# def archives(request,year,month):
#     post_list = Post.objects.filter(created_time__year=year,created_time__month=month).order_by('-created_time')
#     return render(request,'blog/index.html',context={'post_list':post_list})

class ArchivesView(IndexView):
    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(ArchivesView, self).get_queryset().filter(created_time__year=year,
                                                               created_time__month=month
                                                               )

# def category(request, category):
#     cate = get_object_or_404(Category, name=category)
#     post_list = Post.objects.filter(category=cate).order_by('-created_time')
#     return render(request, 'blog/index.html', context={'post_list': post_list})
class CategoryView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category, name=self.kwargs.get('category'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


# def tags(request,tag):
#     a = get_object_or_404(Tag, name=tag)
#     post_list = Post.objects.filter(tags=a).order_by('-created_time')
#     return render(request, 'blog/index.html', context={'post_list':post_list})
class TagView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Tag,name = self.kwargs.get('tag'))
        return super(TagView,self).get_queryset().filter(tags=cate)

def about(request):
    return render(request,'about.html')

def search(request):
    q = request.GET.get('q')
    error_msg = ''
    if not q:
        error_msg = '请输入关键词'
        return render(request, 'blog/index.html', {'error_msg': error_msg})
    post_list = Post.objects.filter(title__icontains=q)
    return render(request, 'blog/index.html', {'error_msg': error_msg,
                                               'post_list': post_list})

comments/views.py
from django.shortcuts import render,get_object_or_404,redirect
from blog.models import Post
from .models import Comment
from .forms import CommentForm

def post_comment(request,post_pk):
    post = get_object_or_404(Post,pk=post_pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect(post)
        else:
            comment_list = post.comment_set.all()
            context = {'post': post,
                       'form': form,
                       'comment_list': comment_list
                       }
            return render(request, 'blog/detail.html', context=context)
    return redirect(post)

templates/about.html
{% extends 'base.html' %}

{% block main %}
	<p>&nbsp;</p>
	<p class="text-center"><strong>关于本站：</strong></p>
	<p class="text-center">Django框架+Sqlite数据库</p>
	<p class="text-center "><strong>感谢以下开源组件：</strong></p>
	<p class="text-center">pytz/markdown/django/Pyments/pip</p>
	<p class="text-center text-danger"><strong>人生苦短，我用Python！</strong></p>
{% endblock main %}
{% block side %}
	<img src="https://ws1.sinaimg.cn/large/e1d172d7ly1fl79fyfjrdj208z05d0td.jpg" alt="王之蔑视">
{% endblock side %}

templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>夜雨 &amp; 君</title>
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/tango.css' %}">

    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}’"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>夜雨 &amp; 菌</b></a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="/about" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="mailto:ghosx@qq.com" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'blog:search' %}">
                            <input type="search" placeholder="搜索" name="q" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
{% block main %}

{% endblock main %}
            </main>

            {% block side %}
            <aside class="col-md-4">

              <!-- ↓最新文章↓ -->
              <div class="widget widget-recent-posts">
              <h3 class="widget-title">最新文章</h3>
              {% get_recent_posts as recent_post_list %}
              <ul>
                {% for post in recent_post_list %}
                <li>
                  <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
                {% empty %}
                暂无文章！
                {% endfor %}
              </ul>
              </div>
              <!-- ↓归档↓ -->
              <div class="widget widget-archives">
                <h3 class="widget-title">归档</h3>
                {% archives as date_list %}
                <ul>
                  {% for date in date_list %}
                  <li>
                    <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
                  </li>
                  {% empty %}
                  暂无归档！
                  {% endfor %}
                </ul>
              </div>
              <!-- ↓ 分类 ↓  -->
              <div class="widget widget-category">
                <h3 class="widget-title">分类</h3>
                {% categories as category_list %}
                <ul>
                  {% for category in category_list %}
                  <li>
                    <a href="{% url 'blog:category' category.name %}">{{ category.name }} <span class="post-count">(1)</span></a>
                  </li>
                  {% empty %}
                  暂无分类！
                  {% endfor %}
                </ul>
              </div>
              <!-- 标签云 -->
              <div class="widget widget-tag-cloud">
                      <h3 class="widget-title">标签云</h3>
                        <ul>
                          {% tags as tag_list %}
                          {% for tag in tag_list %}
                          <li><a href="/tag/{{ tag.name }}/">{{ tag }}</a></li>
                          {% endfor %}
                        </ul>
              </div>
            </aside>
            {% endblock side %}

        </div>
    </div>
</div>

<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">©西安理工大学参赛作品
                </p>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'blog/js/script.js' %}"></script>

</body>
</html>

templates/blog/detail.html
{% extends 'base.html' %}
{% block main %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="#comment-area">{{ comment_list.count }} 评论</a></span>
                <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body|safe }}
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>评论</h3>

        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
          {% csrf_token %}
          <div class="row">
            <div class="col-md-4">
              <label for="{{ form.name.id_for_label }}">Username：</label>
              {{ form.name }}
              {{ form.name.errors }}
            </div>
            <div class="col-md-4">
              <label for="{{ form.email.id_for_label }}">Email：</label>
              {{ form.email }}
              {{ form.email.errors }}
            </div>
            <div class="col-md-4">
              <label for="{{ form.url.id_for_label }}">Website：</label>
              {{ form.url }}
              {{ form.url.errors }}
            </div>
            <div class="col-md-12">
              <label for="{{ form.text.id_for_label }}">Comment：</label>
              {{ form.text }}
              {{ form.text.errors }}
              <button type="submit" class="comment-btn">Biu~ </button>
            </div>
          </div>    <!-- row -->
        </form>


        <div class="comment-list-panel">
            <h3>评论列表，共 <span>{{ comment_list.count }}</span> 条评论</h3>

            <ul class="comment-list list-unstyled">
                  {% for comment in comment_list %}
                  <li class="comment-item">
                    <span class="nickname">{{ comment.name }}</span>
                    <time class="submit-date">{{ comment.created_time }}</time>
                    <div class="text">
                      {{ comment.text }}
                    </div>
                  </li>
                  {% empty %}
                  暂无评论
                  {% endfor %}
            </ul>
        </div>
    </section>
{% endblock main %}
{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        <ul>
            <li>
                <a href="#">教程特点</a>
            </li>
            <li>
                <a href="#">谁适合这个教程</a>
            </li>
            <li>
                <a href="#">在线预览</a>
            </li>
            <li>
                <a href="#">资源列表</a>
            </li>
            <li>
                <a href="#">获取帮助</a>
            </li>
        </ul>
    </div>
{% endblock toc %}

templates/blog/index.html
{% extends 'base.html' %}
{% block main %}
{% if error_msg %}
    <p>{{ error_msg }}</p>
  {% endif %}
{% for post in post_list %}
<article class="post post-1">
    <header class="entry-header">
        <h1 class="entry-title">
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h1>
        <div class="entry-meta">
            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
            <span class="post-date"><a href="#"><time class="entry-date"
                                                      datetime="{{ p.created_time }}">{{ post.created_time }}</time></a></span>
             <span class="post-author"><a href="#">{{ post.author }}</a></span> 
            <span class="comments-link"><a href="{% url 'blog:detail' post.pk %}#comment-area">{{ post.comment_set.count}}评论</a></span>
            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        <p>{{ post.excerpt }}</p>
        <div class="read-more cl-effect-14">
            <a href="{{ post.get_absolute_url }}" class="more-link"> More <span class="meta-nav">→</span></a>
        </div>
    </div>
</article>
{% empty %}
  <div class="no-post">暂时还没有发布的文章！</div>
{% endfor %}
<!-- 简单分页效果 -->
{% if is_paginated %}
              <div class="pagination-simple">
              <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->
              {% if page_obj.has_previous %}
              <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
              {% endif %}
              <!-- 显示当前页面信息 -->
              <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
              <!-- 如果当前页还有下一页，显示一个下一页的按钮 -->
              {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}">下一页</a>
              {% endif %}
              </div>
              {% endif %}
<!-- 分页结束 -->

{% endblock main %}